### PR TITLE
U10: The player can discard an item of his choice from his hand and extend test suite

### PR DESCRIPTION
**Pull request by paul891112**
Implement boolean attribute "discarded" in backend

Extend test suite

### CODE REVIEW

**Comment by C0DECYCLE** [comment]
(PR title)

**Comment by C0DECYCLE** [comment]
(github pr settings)

**Comment by paul891112** [comment]
Squash commit message:

144: Discard tile and extend test suite

**Review by C0DECYCLE — APPROVED** [review]
LGTM

**Pull request merged**
