### PR TITLE
Initial logic and system architecture: Fix names data fields and controller tests

### PR DESCRIPTION
**Pull request by Twhining**

### CODE REVIEW

**Review by C0DECYCLE — CHANGES_REQUESTED** [review]
LGTM but please rebase onto master and adjust pr title and other github stuffs

**Review by C0DECYCLE — CHANGES_REQUESTED** [review]
Change please, thanks!: 
- PR title should start a Userstory
- Github stuff  = assignee etc 
- PR should only consist of your commit

**Comment by Twhining** [comment]
i rebased it from master but the commit doesn't go away can't this be dealt with via squashing? I don't know how to get rid of that commit...

**Comment by C0DECYCLE** [comment]
> i rebased it from master but the commit doesn't go away can't this be dealt with via squashing? I don't know how to get rid of that commit...

Probably but it would be a good practice... try this:
0. If you want to be safe, backup your commit by creating a new local branch from it which you dont push.
1. Reset your local version of your branch to the current master commit
2. Cherrypick your single new commit (then it should be correct)
3. Force push it to the remote
4. In case you made a backup branch in step 0, delete it

**Comment by Twhining** [comment]
i think i did it 🦸

**Comment by Twhining** [comment]
thank youuuuuuuu

**Review by C0DECYCLE — APPROVED** [review]
Amazing, Beautiful! 🥹

**Comment by C0DECYCLE** [comment]
> i think i did it 🦸

Amazing! 😊

**Pull request merged**
